server:
  port: 8082
logging:
  level:
    org:
      springframework:
        web.reactive.function.client.ExchangeFunctions: TRACE
        oauth2.client.endpoint.DefaultAuthorizationCodeTokenResponseClient: DEBUG
        security: DEBUG

spring:
  application:
    name: shuttleverse-gateway

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
  session:
    redis:
      namespace: "shuttleverse:session"
      flush-mode: on-save
    timeout: 24h

  # OAuth2 Configuration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "${BACKEND_BASE_URL:http://localhost:8082}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - email
              - profile

  # Gateway Configuration
  cloud:
    gateway:
      default-filters:
        - SaveSession
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      # Route definitions
      routes:
        - id: shuttleverse-aggregator
          uri: lb://shuttleverse-aggregator
          predicates:
            - Path=/api/aggregator/**

        - id: shuttleverse-community
          uri: lb://shuttleverse-community
          predicates:
            - Path=/api/community/**
  profiles:
    default: dev

jwt:
  secret: ${JWT_SECRET_KEY:-${TEST_JWT_SECRET_KEY}}

eureka:
  client:
    service-url:
      defaultZone: "http://shuttleverse-service-discovery:8761/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
