server:
  port: 8082

spring:
  application:
    name: shuttleverse-gateway

  data:
    redis:
      host: localhost
      port: 6379

  # OAuth2 Configuration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "http://localhost:8082/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - email
              - profile

  # Gateway Configuration
  cloud:
    gateway:
      default-filters:
        - TokenRelay
        - SaveSession

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      # Route definitions
      routes:
        - id: shuttleverse-aggregator
          uri: lb://shuttleverse-aggregator
          predicates:
            - Path=/api/aggregator/**

        - id: shuttleverse-community
          uri: lb://shuttleverse-community
          predicates:
            - Path=/api/community/**

eureka:
  client:
    service-url:
      defaultZone:
        ${EUREKA_SERVER_DEFAULT_ZONE:http://shuttleverse-service-discovery:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always