apiVersion: apps/v1
kind: Deployment
metadata:
  name: shuttleverse-gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shuttleverse-gateway
  template:
    metadata:
      labels:
        app: shuttleverse-gateway
    spec:
      containers:
        - name: shuttleverse-gateway
          image: docker-user/shuttleverse-gateway:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET_KEY
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-client-id
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-client-secret
                  key: GOOGLE_CLIENT_SECRET
            - name: BACKEND_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-base-url
                  key: BACKEND_BASE_URL
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-password
                  key: REDIS_PASSWORD
            - name: JAVA_TOOL_OPTIONS
              value: "-Djavax.net.debug=ssl,handshake, verbose -Djava.net.preferIPv4Stack=true"
---
apiVersion: v1
kind: Service
metadata:
  name: shuttleverse-gateway
  namespace: default
spec:
  selector:
    app: shuttleverse-gateway
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP